// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StoEtDash.Web.Database.Models;

#nullable disable

namespace StoEtDash.Web.Migrations
{
    [DbContext(typeof(StoEtDashContext))]
    partial class StoEtDashContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.3");

            modelBuilder.Entity("StoEtDash.Web.Database.Models.User", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("VARCHAR (60)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("VARCHAR (128)");

                    b.HasKey("Username");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
